soundcloud_conversation_fixture = [{u'attachments': [],
  u'id': u'77871924:6924356',
  u'last_message': {u'content': u'hey',
                    u'conversation_id': u'77871924:6924356',
                    u'sender_type': u'user',
                    u'sender_urn': u'soundcloud:people:77871924',
                    u'sent_at': u'2014/11/04 17:24:20 +0000'},
  u'read': True,
  u'started_at': u'2014/11/04 17:24:20 +0000',
  u'summary': u'...',
  u'users': [{u'avatar_url': u'https://i1.sndcdn.com/avatars-000069217659-8j22kc-large.jpg',
              u'id': 77871924,
              u'kind': u'user',
              u'last_modified': u'2014/11/03 02:53:41 +0000',
              u'online': False,
              u'permalink': u'dogebot',
              u'permalink_url': u'http://soundcloud.com/dogebot',
              u'uri': u'https://api.soundcloud.com/users/77871924',
              u'username': u'dogebot'},
             {u'avatar_url': u'https://a1.sndcdn.com/images/default_avatar_large.png',
              u'id': 6924356,
              u'kind': u'user',
              u'last_modified': u'2014/11/05 16:48:36 +0000',
              u'online': False,
              u'permalink': u'bonbontaq',
              u'permalink_url': u'http://soundcloud.com/bonbontaq',
              u'uri': u'https://api.soundcloud.com/users/6924356',
              u'username': u'Bonbontaq'}]},
 {u'attachments': [],
  u'id': u'77871924:10457497',
  u'last_message': {u'content': u'testesttestst',
                    u'conversation_id': u'77871924:10457497',
                    u'sender_type': u'user',
                    u'sender_urn': u'soundcloud:people:77871924',
                    u'sent_at': u'2014/02/08 22:21:44 +0000'},
  u'read': True,
  u'started_at': u'2014/02/08 22:21:44 +0000',
  u'summary': u'...',
  u'users': [{u'avatar_url': u'https://i1.sndcdn.com/avatars-000069217659-8j22kc-large.jpg',
              u'id': 77871924,
              u'kind': u'user',
              u'last_modified': u'2014/11/03 02:53:41 +0000',
              u'online': False,
              u'permalink': u'dogebot',
              u'permalink_url': u'http://soundcloud.com/dogebot',
              u'uri': u'https://api.soundcloud.com/users/77871924',
              u'username': u'dogebot'},
             {u'avatar_url': u'https://a1.sndcdn.com/images/default_avatar_large.png',
              u'id': 10457497,
              u'kind': u'user',
              u'last_modified': u'2012/01/04 20:24:34 +0000',
              u'online': False,
              u'permalink': u'figtree',
              u'permalink_url': u'http://soundcloud.com/figtree',
              u'uri': u'https://api.soundcloud.com/users/10457497',
              u'username': u'figtree'}]},
 {u'attachments': [],
  u'id': u'77871924:system',
  u'last_message': {u'content': u'\n<html>\n  <body>\n<p>Welcome to SoundCloud! Get ready to discover new music & audio, connect with the SoundCloud community, and share the sounds you love the most with your followers.</p>\n<p>Here\'s how to get started:</p>\n<ul class="bullet"><li><a href="http://help.soundcloud.com/customer/portal/articles/871522-how-do-i-find-sounds-to-listen-to-?utm_campaign=system&amp;utm_content=welcome&amp;utm_medium=notification&amp;utm_source=soundcloud&amp;utm_term=20140130">Find friends and artists you like</a>, and follow them to hear their music & audio and find out what sounds they\u2019re playing.</li>\n<li>Like the sounds you love the most, and <a href="http://help.soundcloud.com/customer/portal/articles/527370-what-are-reposts-?utm_campaign=system&amp;utm_content=welcome&amp;utm_medium=notification&amp;utm_source=soundcloud&amp;utm_term=20140130">repost</a> them for everyone else to hear.</li>\n<li>You have sounds to share? Step by our <a href="https://soundcloud.com/creators?utm_campaign=system&amp;utm_content=welcome&amp;utm_medium=notification&amp;utm_source=soundcloud&amp;utm_term=20140130">Creator Page</a> to get valuable tips on how to share your music & audio, and connect with the community.</li>\n<li><a href="http://help.soundcloud.com/customer/portal/articles/527378-what%E2%80%99s-new-with-sets-in-the-next-soundcloud-and-where-are-they-?utm_campaign=system&amp;utm_content=welcome&amp;utm_medium=notification&amp;utm_source=soundcloud&amp;utm_term=20140130">Curate your own sets</a> to share whole collections of sounds, or repost sets made by other community members.</li>\n</ul><p>Head over to our <a href="http://help.soundcloud.com?utm_campaign=system&amp;utm_content=welcome&amp;utm_medium=notification&amp;utm_source=soundcloud&amp;utm_term=20140130">Help Center</a> if you have any questions.</p></body></html>\n',
                    u'conversation_id': u'system:77871924',
                    u'sender_type': u'system',
                    u'sender_urn': u'soundcloud:users:system',
                    u'sent_at': u'2014/01/30 13:32:21 +0000'},
  u'read': True,
  u'started_at': u'2014/01/30 13:32:21 +0000',
  u'summary': u'...',
  u'users': [{u'avatar_url': u'https://i1.sndcdn.com/avatars-000069217659-8j22kc-large.jpg',
              u'id': 77871924,
              u'kind': u'user',
              u'last_modified': u'2014/11/03 02:53:41 +0000',
              u'online': False,
              u'permalink': u'dogebot',
              u'permalink_url': u'http://soundcloud.com/dogebot',
              u'uri': u'https://api.soundcloud.com/users/77871924',
              u'username': u'dogebot'},
             {u'id': u'system', u'kind': u'system'}]}]

soundcloud_message_fixture = [{
    'content': 'hey\n',
    'conversation_id': '77871924:6924356',
    'sender_type': 'user',
    'sender_urn': 'soundcloud:people:77871924',
    'sent_at': '2014/02/08 16:52:59 +0000'
}, {
    'content': 'back atcha',
    'conversation_id': '77871924:6924356',
    'sender_type': 'user',
    'sender_urn': 'soundcloud:people:77871924',
    'sent_at': '2014/02/08 16:50:06 +0000'
}, {
    'content': 'hi dogebot <3',
    'conversation_id': '6924356:77871924',
    'sender_type': 'user',
    'sender_urn': 'soundcloud:people:6924356',
    'sent_at': '2014/02/02 03:36:22 +0000'
}]

soundcloud_mention_fixture = [{u'comment': {u'body': u'@dogebot: tip 10',
               u'created_at': u'2014/12/02 11:30:44 +0000',
               u'id': 211660222,
               u'timestamp': 15425,
               u'track': {u'artwork_url': None,
                          u'comment_count': 20,
                          u'commentable': True,
                          u'created_at': u'2011/08/24 17:19:37 +0000',
                          u'description': u'',
                          u'download_count': 1,
                          u'download_url': u'https://api.soundcloud.com/tracks/21800761/download',
                          u'downloadable': True,
                          u'duration': 20435,
                          u'embeddable': True,
                          u'embeddable_by': u'all',
                          u'feedable': False,
                          u'genre': u'',
                          u'id': 21800761,
                          u'isrc': u'',
                          u'kind': u'track',
                          u'label_name': u'',
                          u'last_modified': u'2011/08/24 17:21:01 +0000',
                          u'license': u'all-rights-reserved',
                          u'likes_count': 0,
                          u'original_content_size': 3594096,
                          u'permalink': u'ian',
                          u'permalink_url': u'http://soundcloud.com/bonbontaq/ian',
                          u'playback_count': 39,
                          u'policy': u'ALLOW',
                          u'purchase_title': None,
                          u'purchase_url': None,
                          u'release_date': u'',
                          u'reposts_count': 0,
                          u'secret_token': None,
                          u'secret_uri': None,
                          u'sharing': u'public',
                          u'state': u'finished',
                          u'stream_url': u'https://api.soundcloud.com/tracks/21800761/stream',
                          u'streamable': True,
                          u'tag_list': u'Init',
                          u'title': u'ian',
                          u'track_type': u'',
                          u'updated_at': u'2011/08/24 17:21:01 +0000',
                          u'uri': u'https://api.soundcloud.com/tracks/21800761',
                          u'user': {u'avatar_url': u'http://a1.sndcdn.com/images/default_avatar_large.png?1417701725',
                                    u'first_name': None,
                                    u'id': 6924356,
                                    u'kind': u'user',
                                    u'last_modified': u'2014/12/02 10:38:24 +0000',
                                    u'permalink': u'bonbontaq',
                                    u'permalink_url': u'http://soundcloud.com/bonbontaq',
                                    u'uri': u'https://api.soundcloud.com/users/6924356',
                                    u'username': u'Bonbontaq'},
                          u'user_id': 6924356,
                          u'visuals': None,
                          u'waveform_url': u'https://wis.sndcdn.com/TEZ3IMZmLdVo_m.png'},
               u'track_id': 21800761},
  u'created_at': u'2014/12/02 11:30:44 +0000',
  u'type': u'comment',
  u'user': {u'avatar_url': u'http://a1.sndcdn.com/images/default_avatar_large.png?1417701725',
            u'city': None,
            u'country': None,
            u'description': None,
            u'first_name': None,
            u'followers_count': 0,
            u'followings_count': 0,
            u'full_name': u'',
            u'groups_count': 0,
            u'id': 123577402,
            u'kind': u'user',
            u'last_modified': u'2014/12/02 10:38:39 +0000',
            u'permalink': u'yetanothertest',
            u'permalink_url': u'http://soundcloud.com/yetanothertest',
            u'plan': u'Free',
            u'public_favorites_count': 0,
            u'tracks_count': 0,
            u'uri': u'https://api.soundcloud.com/users/123577402',
            u'username': u'666robobo777'},
  u'uuid': u'2014/12/02_11:30:44_+0000_soundcloud:users:123577402_soundcloud:comments:211660222'},
 {u'comment': {u'body': u'@dogebot: tip 20',
               u'created_at': u'2014/12/02 11:29:37 +0000',
               u'id': 211660159,
               u'timestamp': 4545,
               u'track': {u'artwork_url': None,
                          u'comment_count': 20,
                          u'commentable': True,
                          u'created_at': u'2011/08/24 17:19:37 +0000',
                          u'description': u'',
                          u'download_count': 1,
                          u'download_url': u'https://api.soundcloud.com/tracks/21800761/download',
                          u'downloadable': True,
                          u'duration': 20435,
                          u'embeddable': True,
                          u'embeddable_by': u'all',
                          u'feedable': False,
                          u'genre': u'',
                          u'id': 21800761,
                          u'isrc': u'',
                          u'kind': u'track',
                          u'label_name': u'',
                          u'last_modified': u'2011/08/24 17:21:01 +0000',
                          u'license': u'all-rights-reserved',
                          u'likes_count': 0,
                          u'original_content_size': 3594096,
                          u'permalink': u'ian',
                          u'permalink_url': u'http://soundcloud.com/bonbontaq/ian',
                          u'playback_count': 39,
                          u'policy': u'ALLOW',
                          u'purchase_title': None,
                          u'purchase_url': None,
                          u'release_date': u'',
                          u'reposts_count': 0,
                          u'secret_token': None,
                          u'secret_uri': None,
                          u'sharing': u'public',
                          u'state': u'finished',
                          u'stream_url': u'https://api.soundcloud.com/tracks/21800761/stream',
                          u'streamable': True,
                          u'tag_list': u'Init',
                          u'title': u'ian',
                          u'track_type': u'',
                          u'updated_at': u'2011/08/24 17:21:01 +0000',
                          u'uri': u'https://api.soundcloud.com/tracks/21800761',
                          u'user': {u'avatar_url': u'http://a1.sndcdn.com/images/default_avatar_large.png?1417701725',
                                    u'first_name': None,
                                    u'id': 6924356,
                                    u'kind': u'user',
                                    u'last_modified': u'2014/12/02 10:38:24 +0000',
                                    u'permalink': u'bonbontaq',
                                    u'permalink_url': u'http://soundcloud.com/bonbontaq',
                                    u'uri': u'https://api.soundcloud.com/users/6924356',
                                    u'username': u'Bonbontaq'},
                          u'user_id': 6924356,
                          u'visuals': None,
                          u'waveform_url': u'https://wis.sndcdn.com/TEZ3IMZmLdVo_m.png'},
               u'track_id': 21800761},
  u'created_at': u'2014/12/02 11:29:37 +0000',
  u'type': u'comment',
  u'user': {u'avatar_url': u'http://a1.sndcdn.com/images/default_avatar_large.png?1417701725',
            u'city': None,
            u'country': None,
            u'description': None,
            u'first_name': None,
            u'followers_count': 0,
            u'followings_count': 0,
            u'full_name': u'',
            u'groups_count': 0,
            u'id': 123577402,
            u'kind': u'user',
            u'last_modified': u'2014/12/02 10:38:39 +0000',
            u'permalink': u'yetanothertest',
            u'permalink_url': u'http://soundcloud.com/yetanothertest',
            u'plan': u'Free',
            u'public_favorites_count': 0,
            u'tracks_count': 0,
            u'uri': u'https://api.soundcloud.com/users/123577402',
            u'username': u'666robobo777'},
  u'uuid': u'2014/12/02_11:29:37_+0000_soundcloud:users:123577402_soundcloud:comments:211660159'},
 {u'comment': {u'body': u'@dogebot: tip 20',
               u'created_at': u'2014/12/02 11:24:33 +0000',
               u'id': 211659855,
               u'timestamp': 2063,
               u'track': {u'artwork_url': None,
                          u'comment_count': 20,
                          u'commentable': True,
                          u'created_at': u'2011/08/24 17:19:37 +0000',
                          u'description': u'',
                          u'download_count': 1,
                          u'download_url': u'https://api.soundcloud.com/tracks/21800761/download',
                          u'downloadable': True,
                          u'duration': 20435,
                          u'embeddable': True,
                          u'embeddable_by': u'all',
                          u'feedable': False,
                          u'genre': u'',
                          u'id': 21800761,
                          u'isrc': u'',
                          u'kind': u'track',
                          u'label_name': u'',
                          u'last_modified': u'2011/08/24 17:21:01 +0000',
                          u'license': u'all-rights-reserved',
                          u'likes_count': 0,
                          u'original_content_size': 3594096,
                          u'permalink': u'ian',
                          u'permalink_url': u'http://soundcloud.com/bonbontaq/ian',
                          u'playback_count': 39,
                          u'policy': u'ALLOW',
                          u'purchase_title': None,
                          u'purchase_url': None,
                          u'release_date': u'',
                          u'reposts_count': 0,
                          u'secret_token': None,
                          u'secret_uri': None,
                          u'sharing': u'public',
                          u'state': u'finished',
                          u'stream_url': u'https://api.soundcloud.com/tracks/21800761/stream',
                          u'streamable': True,
                          u'tag_list': u'Init',
                          u'title': u'ian',
                          u'track_type': u'',
                          u'updated_at': u'2011/08/24 17:21:01 +0000',
                          u'uri': u'https://api.soundcloud.com/tracks/21800761',
                          u'user': {u'avatar_url': u'http://a1.sndcdn.com/images/default_avatar_large.png?1417701725',
                                    u'first_name': None,
                                    u'id': 6924356,
                                    u'kind': u'user',
                                    u'last_modified': u'2014/12/02 10:38:24 +0000',
                                    u'permalink': u'bonbontaq',
                                    u'permalink_url': u'http://soundcloud.com/bonbontaq',
                                    u'uri': u'https://api.soundcloud.com/users/6924356',
                                    u'username': u'Bonbontaq'},
                          u'user_id': 6924356,
                          u'visuals': None,
                          u'waveform_url': u'https://wis.sndcdn.com/TEZ3IMZmLdVo_m.png'},
               u'track_id': 21800761},
  u'created_at': u'2014/12/02 11:24:33 +0000',
  u'type': u'affiliation',
  u'user': {u'avatar_url': u'http://a1.sndcdn.com/images/default_avatar_large.png?1417701725',
            u'city': None,
            u'country': None,
            u'description': None,
            u'first_name': None,
            u'followers_count': 0,
            u'followings_count': 0,
            u'full_name': u'',
            u'groups_count': 0,
            u'id': 123577402,
            u'kind': u'user',
            u'last_modified': u'2014/12/02 10:38:39 +0000',
            u'permalink': u'yetanothertest',
            u'permalink_url': u'http://soundcloud.com/yetanothertest',
            u'plan': u'Free',
            u'public_favorites_count': 0,
            u'tracks_count': 0,
            u'uri': u'https://api.soundcloud.com/users/123577402',
            u'username': u'666robobo777'},
  u'uuid': u'2014/12/02_11:24:33_+0000_soundcloud:users:123577402_soundcloud:comments:211659855'}]


soundcloud_resolve_user_fixture = {u'avatar_url': u'https://i1.sndcdn.com/avatars-000069217659-8j22kc-large.jpg',
 u'city': None,
 u'country': None,
 u'description': u'Not operating yet, but close!\r\n\r\nDoge.  Sound.  Doge.  Cloud.',
 u'discogs_name': None,
 u'first_name': None,
 u'followers_count': 1,
 u'followings_count': 56,
 u'full_name': u'',
 u'id': 77871924,
 u'kind': u'user',
 u'last_modified': u'2014/11/26 23:08:50 +0000',
 u'last_name': None,
 u'myspace_name': None,
 u'online': False,
 u'permalink': u'dogebot',
 u'permalink_url': u'http://soundcloud.com/dogebot',
 u'plan': u'Free',
 u'playlist_count': 0,
 u'public_favorites_count': 0,
 u'subscriptions': [],
 u'track_count': 1,
 u'uri': u'https://api.soundcloud.com/users/77871924',
 u'username': u'dogebot',
 u'website': None,
 u'website_title': None}

wallet_transactions_fixture = [{u'account': u'users',
  u'amount': -400.0,
  u'category': u'move',
  u'comment': u'',
  u'otheraccount': u'dkd',
  u'time': 1418598384},
 {u'account': u'users',
  u'amount': 400.0,
  u'category': u'move',
  u'comment': u'',
  u'otheraccount': u'dkd',
  u'time': 1418598411},
 {u'account': u'users',
  u'amount': 400.0,
  u'category': u'move',
  u'comment': u'',
  u'otheraccount': u'dkd',
  u'time': 1418598420},
 {u'account': u'users',
  u'address': u'nfcs52piVXTkvVwBu7L3FGzV663mapMSao',
  u'amount': 100.0,
  u'blockhash': u'5aa2b2c40f697313de18f633f1c3ed9b08070544e87a348e81c964ba3d1c11bb',
  u'blockindex': 1,
  u'blocktime': 1418617133,
  u'category': u'receive',
  u'confirmations': 42,
  u'time': 1418616853,
  u'timereceived': 1418616853,
  u'txid': u'bafe23fc47d4d5b4e9f188264c8de4e82e5134be1a93d6053f5010a58b85d65d',
  u'walletconflicts': []}]
